### ISSUE TITLE
Login fails with a non-ldap django user

### ISSUE THREAD

**Issue by nikhil** [mskcc/seqosystem#49]
equest: GET /
** (exit) an exception was raised:
    ** (KeyError) key :access_token not found in: #Ecto.Changeset<action: :update, changes: %{access_token: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjA3NjE4MDQ2LCJqdGkiOiIzODE1NzM5NjUyMmI0M2U1OTI0MjdlYmFlZjI0M2Y3OSIsInVzZXJfaWQiOjEsInVzZXIiOnsiZW1haWwiOiIiLCJncm91cHMiOlsibXNrY2MiXX19.FxAWhAEizJpPzsd8WWIzqpPg-fGBxx4E1pXegFNwZBM"}, errors: [email: {"can't be blank", [validation: :required]}], data: #Domain.Accounts.User<>, valid?: false>
        (dashboard 0.0.1+f815928) lib/dashboard/user_auth.ex:103: Dashboard.UserAuth.fetch_current_user/2
        (voyager 0.1.0+f815928) VoyagerWeb.Router.browser/2
        (voyager 0.1.0+f815928) lib/voyager_web/router.ex:1: VoyagerWeb.Router.__pipe_through1__/1
        (phoenix 1.5.7) lib/phoenix/router.ex:347: Phoenix.Router.__call__/2
        (voyager 0.1.0+f815928) lib/voyager_web/endpoint.ex:1: VoyagerWeb.Endpoint.plug_builder_call/2
        (voyager 0.1.0+f815928) lib/voyager_web/endpoint.ex:1: VoyagerWeb.Endpoint.call/2
        (phoenix 1.5.7) lib/phoenix/endpoint/cowboy2_handler.ex:65: Phoenix.Endpoint.Cowboy2Handler.init/4
        (cowboy 2.8.0) /juno/work/seqosystem/temp/builds/deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2

**Comment by nikhil** [comment]
Resolved by #52
